[
  {
    categories: [26163113031],
    imagesCSV:
      '51GGiVeINkL.jpg,51iALTXpK3L.jpg,41DvzKdgXrL.jpg,51QnGZ6MurL.jpg,51clr9uYFcL.jpg,51reHwpKccL.jpg,31e76gSYB0S.jpg,41E5PFUGJcS.jpg,41r8d8-7-vS.jpg,31pzW5E20tL.jpg,31YfFMpy9wS.jpg,41SSABsG+xS.jpg,515Z2OgEMnS.jpg,519uy8qRBUS.jpg',
    manufacturer: 'LEGO',
    title:
      'LEGO 31088 Creator Bewohner der Tiefsee, Spielzeug mit Meerestieren Figuren: Hai, Krabbe, Tintenfisch und Seeteufel, Set für Kinder ab 7 Jahre',
    asin: 'B07FNS6J7R',
    brand: 'LEGO',
    productGroup: 'Toy',
    color: 'Mehrfarbig',
    packageHeight: 50,
    packageLength: 262,
    packageWidth: 142,
    packageWeight: 320,
    packageQuantity: 1,
    isAdultProduct: false,
    author: 'LEGO',
    binding: 'Spielzeug',
    eanList: ['5702016367836'],
    upcList: null,
    frequentlyBoughtTogether: ['B08G4P2B7B', 'B07W5PW3KV'],
    features: [
      'Mit diesem LEGO Creator 3-in-1-Set für Kinder ab 7 Jahre lassen sich 3 Meerestiere Figuren bauen!',
      'Baue den Spielzeug Hai mit der Krabbe und der Schatztruhe und verwandle ihn dann in einen beweglichen Tintenfisch oder einen Spielzeug Seeteufel mit riesigem Maul',
      'Das Set Bewohner der Tiefsee enthält einen unheimlichen Spielzeug Hai mit aufklappbarem Maul, spitzen Zähnen, beweglichen Flossen, beweglichen Gelenken und reflektierenden Augen',
      'Sieh dir die coole blau-weiße Farbgebung des Hais an! Dieses LEGO Meerestiere-Set ist das perfekte Geschenk für Jungen und Mädchen, die Figuren lieben',
      'Das Set bietet sogar noch eine zusätzliche Baumöglichkeit und eine Bauanleitung für einen Wal  erhältlich auf LEGO.com',
    ],
    description:
      'Produktbeschreibung      Erlebe mit dem LEGO Creator 3-in-1-Set Bewohner der Tiefsee (31088) spannende Unterwasserabenteuer. Das Set enthält einen unheimlichen Spielzeug-Hai in authentischer blauer und weißer Farbe mit aufklappbarem Maul voller spitzer Zähne, beweglichen Flossen, beweglichen Gelenken und reflektierenden Augen sowie eine bewegliche Krabbe mit einer Schatztruhe. Die LEGO Creator 3-in-1-Spielsets bieten dir drei verschiedene Bau- und Spielerlebnisse. Baue zunächst einen Hai und eine Krabbe. Anschließend kannst du sie für noch mehr Unterwasserspaß in einen beweglichen Tintenfisch oder einen Seeteufel mit riesigem Maul umbauen.      Warnhinweise      Achtung. Nicht geeignet für Kinder unter 36 Monate. Enthält verschluckbare Kleinteile. Erstickungsgefahr.      Rechtliche Hinweise      Achtung. Nicht geeignet für Kinder unter 36 Monate. Enthält verschluckbare Kleinteile.',
    itemHeight: 141,
    itemLength: 262,
    itemWidth: 48,
    itemWeight: 312,
    categoryTree: [
      {
        catId: 12950651,
        name: 'Spielzeug',
      },
      {
        catId: 360407031,
        name: 'Bau- & Konstruktionsspielzeug',
      },
      {
        catId: 26163113031,
        name: 'Bauspielzeugsets',
      },
    ],
  },
  {
    categories: [360407031],
    imagesCSV:
      '51xULHfX3lL.jpg,41oRpLhYQnL.jpg,41LOMkKL6SL.jpg,41DzXT6RnbL.jpg,51QraR88vBL.jpg,41e6GqPppQL.jpg,51NnbyJ5bFL.jpg,41xSx57KWlS.jpg,51NEx03cxzS.jpg,51M0SMxAYPS.jpg,61q9RYHrDtS.jpg,51jpJV9tCIS.jpg,51tdjIa7AbL.jpg,41Zw-DFz1KS.jpg,41t3TC0uyiS.jpg,41S5F6evDES.jpg,51P0zPdVBES.jpg',
    manufacturer: 'LEGO',
    title:
      'LEGO 31102 Creator 3in1 Feuerdrache - Säbelzahntiger - Skorpion, Spielzeug mit Drachen und exotischen Tieren für Mädchen und Jungen ab 7 Jahre',
    asin: 'B07W5PW3KV',
    brand: 'LEGO',
    productGroup: 'Toy',
    color: 'Mehrfarbig',
    packageHeight: 47,
    packageLength: 259,
    packageWidth: 189,
    packageWeight: 350,
    packageQuantity: -1,
    isAdultProduct: false,
    author: null,
    binding: 'Spielzeug',
    eanList: ['5702016616286'],
    upcList: null,
    frequentlyBoughtTogether: ['B08G4P2B7B', 'B01J41DNWM'],
    features: [
      'Dieses faszinierende 3-in-1-Spielzeugset ermöglicht fantasievolle Rollenspiele mit 3 Modellen: einem Feuerdrachen, einem Säbelzahntiger und einem Skorpion. Das Set ist ein tolles Geschenk für Kinder, denn sie können die Modelle immer wieder bauen und umbauen',
      'Wer traut sich, diesen Geschöpfen gegenüberzutreten Kinder entwickeln bessere Baufähigkeiten, wenn sie mit einem Feuerdrachen fliegen, einem Säbelzahntiger entgegentreten oder einem Skorpion ausweichen. Noch kreativer werden sie allerdings, wenn sie bauen, wozu sie Lust haben',
      'Das Creator 3-in-1-Set Feuerdrache (31102) bietet Kindern 3 Bauoptionen: Beim Bauen des Feuerdrachens, des Säbelzahntigers oder des Skorpions entwickeln sie bessere Baufähigkeiten. Die eigenständigen Modelle lassen sich auch mit anderen LEGO Sets kombinieren',
      'Fans des kreativen Bauens werden dieses coole Set lieben. Der rot-blau-gelbe Feuerdrache, der getarnte Säbelzahntiger und der flinke Skorpion sind ein tolles Geschenk zu jedem Anlass für Jungen und Mädchen ab 7 Jahren',
      'Beweglich und für jedes Abenteuer bereit Der Feuerdrache ist 11 cm hoch, 32 cm lang und 25 cm breit. Mit diesen Maßen ist dieses unglaubliche Action-Spielzeug groß genug, um spannende Fantasy-Abenteuer zu erleben',
      'Die Fantasie der Kinder reicht als Antrieb für stundenlangen Spielspaß Spielzeuge ohne Batterie ermöglichen selbstständiges Spielen und fördern die Problemlösefähigkeit. Außerdem macht es Kindern große Freude, sich eigene Geschichten mit diesen Modellen auszudenken',
      'Nach dem Öffnen der Box kann der Spielspaß sofort beginnen, indem die Kinder gleich eines der drei Modelle bauen. Einfache Bauanleitungen erleichtern es den Kindern, die Modelle im Handumdrehen zu bauen, was sie mit Stolz und großer Freude an der eigenen Kreativität erfüllt',
      'LEGO Creator 3-in-1-Sets eröffnen Kindern endlose Spielmöglichkeiten. Dieses coole Tierspielzeug fördert die Kreativität und die Entwicklung von Baufähigkeiten, wenn sich Kinder bei jedem Umbau neue Geschichten ausdenken',
      'LEGO Steine entsprechen den höchsten Branchenstandards, damit sie sich stets mühelos kombinieren, zusammenstecken und wieder zerlegen lassen  und das schon seit 1958',
      'Bei der LEGO Gruppe werden die LEGO Steine und Teile strengen Fall-, Druck-, Torsions-, Hitze-, Biss-, Biege-, Kratz- und Zugtests unterzogen, damit jedes Bauspielzeug für Kinder die höchsten globalen Sicherheits- und Qualitätsstandards erfüllt',
    ],
    description:
      'Produktbeschreibung      Mit dem LEGO Creator 3-in-1-Set Feuerdrache (31102) lassen sich Kinder für coole Geschöpfe und kreativen Bau- und Spielspaß begeistern. Kinder lieben es, mit diesem feuerspeienden Drachen zu spielen, denn sein Kopf, sein Maul, seine Beine, sein Schwanz, seine Flügel und seine Klauen lassen sich bewegen. Außerdem enthält das Set eine aufklappbare Schatztruhe mit verschiedenen Elementen. Freiheit beim Bauen und Spielen Dieses LEGO Creator 3-in-1-Set bereitet Kindern mit den drei verschiedenen Bau- und Spielerlebnissen große Freude. Sie können einen Feuerdrachen erschaffen und dann in einen Säbelzahntiger mit beweglichen Gliedern sowie beweglichem Kopf und Maul, in einen Skorpion mit beweglichen Beinen und Scheren oder in etwas völlig anderes umbauen. Dieses Bauspielzeug inspiriert zu fantasievollen Spielerlebnissen und eignet sich wunderbar als Geschenk für jeden Anlass. Modelle von bekannten Fabelwesen und echten Tieren LEGO Creator 3-in-1-Sets enthalten besonders detailreiche Kinderspielzeuge, sprechen verschiedene Interessen an und inspirieren zu fantasievollem Spielen. Die Modelle bieten unzählige Bau- und Spieloptionen und fördern die Kreativität von Kindern jeden Alters.      Warnhinweise      Achtung. Nicht geeignet für Kinder unter 36 Monate. Enthält verschluckbare Kleinteile. Erstickungsgefahr.',
    itemHeight: 191,
    itemLength: 46,
    itemWidth: 262,
    itemWeight: 0,
    categoryTree: [
      {
        catId: 12950651,
        name: 'Spielzeug',
      },
      {
        catId: 360407031,
        name: 'Bau- & Konstruktionsspielzeug',
      },
    ],
  },
  {
    categories: [360407031],
    imagesCSV:
      '51kdCP4B4pL.jpg,51a6KgonTIS.jpg,41neVOd3D0S.jpg,41j21ygNsWS.jpg,51uXrzvl6LS.jpg,5163IrA-IES.jpg,51oXg+0xMcS.jpg,517gT+9VImL.jpg,51lWLp7APaL.jpg,518tV+fFzBL.jpg,51LOeUuGDkL.jpg,51uuVquaLbL.jpg,51tx3LU54NL.jpg,51knck5uVHL.jpg,41ldOE1aTaL.jpg,51tzmS1bLLL.jpg,51TeGjRBFdS.jpg,41WcIb35U7S.jpg,51L5wnrp7fS.jpg',
    manufacturer: 'LEGO',
    title:
      'LEGO 31112 Creator 3-in-1 Wilder Löwe Set mit Vogel, Strauß und Warzenschwein Tierfiguren, Lernspielzeug, Konstruktionsspielzeug für Kinder ab 7 Jahre',
    asin: 'B08G4P2B7B',
    brand: 'LEGO',
    productGroup: 'Toy',
    color: 'Mehrfarbig',
    packageHeight: 54,
    packageLength: 262,
    packageWidth: 194,
    packageWeight: 310,
    packageQuantity: 1,
    isAdultProduct: false,
    author: null,
    binding: 'Spielzeug',
    eanList: ['8003558361205', '0648596587408', '5702016888348'],
    upcList: ['648596587408'],
    frequentlyBoughtTogether: ['B01J41DNWM', 'B07W5PW3KV'],
    features: [
      'Enthält 3 LEGO Tierfiguren in 1  einen wilden Löwen, einen Vogel Strauß und ein Warzenschwein, sowie einen Geier und abgenagte Rippen, die zu spannenden Geschichten inspirieren',
      'Die 3 Tierfiguren sind äußerst gelenkig: Der Löwe kann seine Beine, seinen Schwanz, seinen Kopf und seinen Kiefer bewegen. Der Strauß hat einen flexiblen Hals und flexible Beine',
      'Auch das Warzenschwein kann Beine, Kopf und Kiefer bewegen. Der Geier kann mit allen 3 Modellen verwendet werden und bietet Kindern noch mehr Spaß bei ihren Savannen-Abenteuern',
      'Dieses 224-teilige LEGO Creator 3-in-1-Set ist ein witziges Lernspielzeug für Kinder ab 7 Jahre und eine tolle Belohnung für kreative Baumeister',
      'LEGO Creator 3-in-1 Konstruktionsspielzeug enthalten 3 verschiedene, farbenfrohe Modelle in jeder Box und ermöglichen es Kindern, unzählige kreative und packende Action-Abenteuer zu erleben',
      'Entdecke auch die anderen LEGO-Creator-3-in-1-Sets: Cyber-Drohne (31111), Rennwagentransporter (31113), Geländemotorrad (31114) und Surfer-Strandhaus (31118)',
    ],
    description:
      'Produktbeschreibung      Das beeindruckende LEGO Creator 3-in-1-Spielset Wilder Löwe (31112) ermöglicht Kindern spannende Tierabenteuer in der Wüste. Es enthält einen Löwen als Modell aus LEGO Steinen mit beweglichen Gliedmaßen sowie einen Geier und Rippenknochen. Kinderspielzeug für fantasievollen Spielspaß Junge Baumeister werden es lieben, die 3 verschiedenen Spielzeugtiere aus diesem LEGO Creator 3-in-1-Set zu bauen. Der wilde Löwe lässt sich auch in einen Strauß oder ein Warzenschwein umbauen oder in ein eigenes cooles Tier verwandeln. Der Geier passt zu allen 3 Modellen. Kreative Geschenke LEGO Creator 3-in-1-Sets enthalten jeweils 3 verschiedene Modelle für unzählige packende Abenteuer und Spielmöglichkeiten! Kinder können die detailreichen Modelle beliebig oft zerlegen, um wieder etwas Neues zu erschaffen. Das Spektrum der fantastischen 3-in-1-Spielsets umfasst Tiere, Fahrzeuge und coole Häuser.      Warnhinweise      Achtung. Nicht geeignet für Kinder unter 36 Monate. Enthält verschluckbare Kleinteile. Erstickungsgefahr.',
    itemHeight: 141,
    itemLength: 48,
    itemWidth: 262,
    itemWeight: 310,
    categoryTree: [
      {
        catId: 12950651,
        name: 'Spielzeug',
      },
      {
        catId: 360407031,
        name: 'Bau- & Konstruktionsspielzeug',
      },
    ],
  },
];
